#factstore1=path/to/kb1
#factstore2=path/to/kb2
#resultTSV=path/to/outputfolder
#home=path/to/outputfolder

endIteration=20
nThreads=4
joinLengthLimit=1
sumJoinLengthLimit=2
bothWays=true
takeMax=true
takeMaxMax=true
lastPassThreshold=0
interestingnessThreshold=false
useNewEqualityProduct=false
matrixSubRelationStores=true
normalizeStrings=false
normalizeDatesToYears=false
shinglingSize=4
shinglingFunctions=30
shinglingTableSize=10485760
shinglingThreads=4
precomputeShinglings=false
shinglingSquare=true
penalizeApproxMatches=1.1
noApproxIfExact=true
parallelFileLoad=true
smoothNumerator=0.0
smoothDenominator=10.0
smoothNumeratorSampling=0.0
smoothDenominatorSampling=1.0
debugEntity=
reportInterval=5000
sampleEntities=0
shuffleEntities=true
cleverMatching=false
postLiteralDistanceThreshold=0.78
allowLoops=false
printNeighborhoodsSampling=false
optimizeNoJoins=true
joinThreshold=0.1
debugSampling=false
literalDistance=identity
