docker_build:
	docker build -t kgt/ontoea .

docker_test:
	echo "Not implemented yet"

docker_help:
	echo "Example usage of OntoEA Docker"
	echo "=== Usage 1 ==="
	echo "docker run --rm kgt/ontoea bash ontoea.sh $args_file $benchmark $splits"
	echo "=== Usage 2 ==="
	echo "docker run --rm kgt/ontoea python main_from_args.py $args_file $benchmark $splits"

