#!/usr/bin/env python3
"""Generate tools/README.md catalog listings from tools/*/tool.yaml manifests."""

import argparse
import sys
from collections import defaultdict
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from catalog_util import (  # noqa: E402
    has_local_kgpipe,
    has_wrapper,
    humanize_category,
    kgpipe_refs,
    load_category_meta,
    load_featured_ids,
    load_manifests,
    require_featured_ids,
)

README_PATH = SCRIPTS_DIR.parent / "tools" / "README.md"

README_HEADER = """<!-- Generated by _scripts/gen_readme.py. Do not edit by hand. -->

# Tool catalog

Tools in this repository, grouped by category.

- **wrapper** — CLI wrapper under `docker/wrapper/` (or a `*wrapper*` script)
- **kgpipe** — KGpipe task names from `tool.yaml`; *defined here* if `kgpipe/` lives in this repo

"""


def format_markers(manifest):
    tool_dir = manifest["_path"]
    tool_id = manifest["id"]
    parts = ["*({})*".format(manifest["status"])]
    if has_wrapper(tool_dir):
        parts.append("wrapper")
    refs = kgpipe_refs(manifest)
    local = has_local_kgpipe(tool_dir)
    if refs or local:
        kgpipe = "kgpipe"
        if refs:
            kgpipe += ": " + ", ".join("`{}`".format(ref) for ref in refs)
        if local:
            kgpipe += " ([defined here]({}/kgpipe/))".format(tool_id)
        parts.append(kgpipe)
    return " · ".join(parts)


def format_tool_line(manifest):
    description = (manifest.get("description") or "").strip()
    name = manifest["name"]
    tool_id = manifest["id"]
    markers = format_markers(manifest)
    if description:
        return "- **[{name}]({id}/README.md)** — {description} {markers}".format(
            name=name, id=tool_id, description=description, markers=markers
        )
    return "- **[{name}]({id}/README.md)** {markers}".format(
        name=name, id=tool_id, markers=markers
    )


def generate_featured(manifests, featured_ids):
    by_id = require_featured_ids(manifests, featured_ids)
    if not featured_ids:
        return ""
    lines = ["## Featured", ""]
    for tool_id in featured_ids:
        lines.append(format_tool_line(by_id[tool_id]))
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_listings(manifests, categories):
    by_category = defaultdict(list)
    for manifest in manifests:
        for cat in manifest.get("categories", ["DatasetUtility"]):
            by_category[cat].append(manifest)

    ordered = [key for key in categories if key in by_category]
    extra = sorted(key for key in by_category if key not in categories)

    lines = []
    for category in ordered + extra:
        lines.append("## {}".format(humanize_category(category)))
        lines.append("")
        cat_desc = categories.get(category, {}).get("description")
        if cat_desc:
            lines.append(cat_desc.rstrip("."))
            lines.append("")
        for manifest in sorted(by_category[category], key=lambda item: item["name"].lower()):
            lines.append(format_tool_line(manifest))
        lines.append("")
    return "\n".join(lines) + "\n"


def render_readme(manifests):
    categories = load_category_meta()
    featured_ids = load_featured_ids()
    return (
        README_HEADER
        + generate_featured(manifests, featured_ids)
        + generate_listings(manifests, categories)
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    manifests = load_manifests()
    if not manifests:
        print("No manifests found.", file=sys.stderr)
        return 1

    content = render_readme(manifests)
    if not content.endswith("\n"):
        content += "\n"

    if args.stdout:
        print(content, end="")
        return 0

    if args.check:
        current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else ""
        if current != content:
            print(
                "tools/README.md is out of date. Run: python _scripts/gen_readme.py",
                file=sys.stderr,
            )
            return 1
        print("tools/README.md is up to date.")
        return 0

    with open(str(README_PATH), "w", encoding="utf-8") as f:
        f.write(content)
    print("Wrote {} ({} tools).".format(README_PATH, len(manifests)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
