#!/usr/bin/env python3
"""Generate the searchable GitHub Pages catalog table from tool.yaml manifests."""

import argparse
import html
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from catalog_util import (  # noqa: E402
    GITHUB_REPO,
    has_local_kgpipe,
    has_wrapper,
    humanize_category,
    kgpipe_refs,
    load_featured_ids,
    load_manifests,
    require_featured_ids,
)
from kgpipe_catalog import collect_kgpipe_tasks, load_task_report  # noqa: E402

PAGES_PATH = SCRIPTS_DIR.parent / "docs" / "index.md"

STATUS_LABEL = {
    "maintained": "label-green",
    "experimental": "label-yellow",
    "deprecated": "label-red",
    "archived": "label",
}

TOOL_TABLE_CLOSE = """</tbody>
</table>
</div>
"""

PAGE_SCRIPT = """
<script src="{{ '/assets/js/catalog-filter.js' | relative_url }}"></script>
"""

STATUS_ORDER = ("maintained", "experimental", "deprecated", "archived")


def catalog_stats(manifests, featured_ids):
    featured_set = set(featured_ids)
    status_counts = {}
    wrappers = 0
    kgpipe = 0
    featured = 0
    for manifest in manifests:
        status_counts[manifest["status"]] = status_counts.get(manifest["status"], 0) + 1
        if has_wrapper(manifest["_path"]):
            wrappers += 1
        if kgpipe_refs(manifest) or has_local_kgpipe(manifest["_path"]):
            kgpipe += 1
        if manifest["id"] in featured_set:
            featured += 1
    return {
        "total": len(manifests),
        "featured": featured,
        "wrappers": wrappers,
        "kgpipe": kgpipe,
        "status_counts": status_counts,
    }


def status_badges(status_counts):
    parts = []
    for status in STATUS_ORDER:
        count = status_counts.get(status, 0)
        if not count:
            continue
        css = STATUS_LABEL.get(status, "label")
        parts.append(
            '<span class="label {}">{} {}</span>'.format(css, count, html.escape(status))
        )
    return "".join(parts)


def render_header(stats):
    return """---
title: Catalog
layout: home
nav_order: 1
description: Searchable catalog of knowledge graph integration tools.
---

<!-- Generated by _scripts/gen_pages.py. Do not edit by hand. -->

<p>Filter by name, description, category, status, wrapper, or KGpipe task.
The markdown catalog in the repository is <a href="{repo}/blob/main/tools/README.md">tools/README.md</a>.</p>

<div class="catalog-stats" aria-label="Catalog summary">
  <div class="catalog-stat"><strong>{total}</strong><span>tools</span></div>
  <div class="catalog-stat"><strong>{featured}</strong><span>featured</span></div>
  <div class="catalog-stat"><strong>{wrappers}</strong><span>wrappers</span></div>
  <div class="catalog-stat"><strong>{kgpipe}</strong><span>KGpipe</span></div>
  <div class="catalog-stat catalog-stat-status">{badges}</div>
</div>

<label for="catalog-filter">Search</label>
<input type="search" id="catalog-filter" placeholder="Filter tools…" aria-controls="tool-catalog" autocomplete="off" data-catalog-filter="tool-catalog" data-catalog-visible="catalog-visible" data-catalog-empty="catalog-empty">

<p id="catalog-shown"><span id="catalog-visible">{total}</span> shown</p>
<p id="catalog-empty" hidden>No tools match.</p>

<div class="catalog-table-wrap">
<table id="tool-catalog">
<thead>
<tr>
<th>Tool</th>
<th>Description</th>
<th>Categories</th>
<th>Status</th>
<th>Wrapper</th>
<th>KGpipe</th>
</tr>
</thead>
<tbody>
""".format(
        repo=GITHUB_REPO,
        total=stats["total"],
        featured=stats["featured"],
        wrappers=stats["wrappers"],
        kgpipe=stats["kgpipe"],
        badges=status_badges(stats["status_counts"]),
    )


def tool_readme_url(tool_id):
    return "{}/blob/main/tools/{}/README.md".format(GITHUB_REPO, tool_id)


def local_kgpipe_url(tool_id):
    return "{}/tree/main/tools/{}/kgpipe".format(GITHUB_REPO, tool_id)


def status_cell(status):
    css = STATUS_LABEL.get(status, "label")
    return '<span class="label {}">{}</span>'.format(css, html.escape(status))


def kgpipe_cell(manifest):
    tool_dir = manifest["_path"]
    tool_id = manifest["id"]
    refs = kgpipe_refs(manifest)
    local = has_local_kgpipe(tool_dir)
    if not refs and not local:
        return "—"
    parts = ["<code>{}</code>".format(html.escape(ref)) for ref in refs]
    if local:
        parts.append(
            '<a href="{}">defined here</a>'.format(html.escape(local_kgpipe_url(tool_id), quote=True))
        )
    return ", ".join(parts)


def table_row(manifest, featured_ids):
    tool_id = manifest["id"]
    name = html.escape(manifest["name"])
    description = html.escape((manifest.get("description") or "").strip() or "—")
    categories = ", ".join(
        html.escape(humanize_category(cat)) for cat in manifest.get("categories", [])
    )
    featured = ""
    if tool_id in featured_ids:
        featured = ' <span class="label label-blue">featured</span>'
    wrapper = "yes" if has_wrapper(manifest["_path"]) else "—"
    href = html.escape(tool_readme_url(tool_id), quote=True)
    return (
        "<tr>"
        '<td><a href="{href}">{name}</a>{featured}</td>'
        "<td>{description}</td>"
        "<td>{categories}</td>"
        "<td>{status}</td>"
        "<td>{wrapper}</td>"
        "<td>{kgpipe}</td>"
        "</tr>"
    ).format(
        href=href,
        name=name,
        featured=featured,
        description=description,
        categories=categories,
        status=status_cell(manifest["status"]),
        wrapper=wrapper,
        kgpipe=kgpipe_cell(manifest),
    )


def task_report_status(task_name, report):
    cases = [case for case in report.get("cases") or [] if case.get("task") == task_name]
    if not cases:
        return None
    outcomes = {case.get("outcome") for case in cases}
    if "failed" in outcomes or "error" in outcomes:
        return "failed"
    if outcomes <= {"skipped"}:
        return "skipped"
    if "passed" in outcomes:
        return "passed"
    return cases[-1].get("outcome")


def report_status_cell(status):
    if not status:
        return "—"
    css = {
        "passed": "label-green",
        "failed": "label-red",
        "skipped": "label-yellow",
        "error": "label-red",
    }.get(status, "label")
    return '<span class="label {}">{}</span>'.format(css, html.escape(status))


def task_table_row(row, report):
    task = html.escape(row["task"])
    tool_id = row["tool"]
    tool_href = html.escape(tool_readme_url(tool_id), quote=True)
    tool = '<a href="{}">{}</a>'.format(tool_href, html.escape(tool_id))
    source = (
        '<a href="{}">local</a>'.format(html.escape(local_kgpipe_url(tool_id), quote=True))
        if row["local"]
        else "ref"
    )
    has_test = "yes" if row["tests"] else "—"
    status = report_status_cell(task_report_status(row["task"], report))
    return (
        "<tr>"
        "<td><code>{task}</code></td>"
        "<td>{tool}</td>"
        "<td>{source}</td>"
        "<td>{has_test}</td>"
        "<td>{status}</td>"
        "</tr>"
    ).format(task=task, tool=tool, source=source, has_test=has_test, status=status)


def render_task_catalog(manifests):
    rows = collect_kgpipe_tasks(manifests)
    report = load_task_report()
    tested = sum(1 for row in rows if row["tests"])
    generated = report.get("generated_at") or "never"
    body = "\n".join(task_table_row(row, report) for row in rows)
    return """
<h2 id="kgpipe-tasks">KGpipe tasks</h2>

<p>Pytest cases live under <code>tools/&lt;id&gt;/kgpipe/tests/</code> and are <strong>not</strong>
run in CI. Generate <code>catalog/reports/kgpipe-tasks.json</code> locally with
<code>python _scripts/manage.py kgpipe-test</code>, then regenerate this page.
Last report: {generated}.</p>

<div class="catalog-stats" aria-label="KGpipe task summary">
  <div class="catalog-stat"><strong>{total}</strong><span>tasks</span></div>
  <div class="catalog-stat"><strong>{tested}</strong><span>with pytest</span></div>
</div>

<label for="task-filter">Search tasks</label>
<input type="search" id="task-filter" placeholder="Filter tasks…" aria-controls="task-catalog" autocomplete="off" data-catalog-filter="task-catalog" data-catalog-visible="task-visible" data-catalog-empty="task-empty">

<p id="task-shown"><span id="task-visible">{total}</span> shown</p>
<p id="task-empty" hidden>No tasks match.</p>

<div class="catalog-table-wrap">
<table id="task-catalog">
<thead>
<tr>
<th>Task</th>
<th>Tool</th>
<th>Defined</th>
<th>Pytest</th>
<th>Report</th>
</tr>
</thead>
<tbody>
{body}
</tbody>
</table>
</div>
""".format(
        generated=html.escape(str(generated)),
        total=len(rows),
        tested=tested,
        body=body,
    )


def render_page(manifests):
    featured_ids = load_featured_ids()
    require_featured_ids(manifests, featured_ids)
    featured_set = set(featured_ids)
    stats = catalog_stats(manifests, featured_ids)
    rows = [
        table_row(manifest, featured_set)
        for manifest in sorted(manifests, key=lambda item: item["name"].lower())
    ]
    return (
        render_header(stats)
        + "\n".join(rows)
        + "\n"
        + TOOL_TABLE_CLOSE
        + render_task_catalog(manifests)
        + PAGE_SCRIPT
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    manifests = load_manifests()
    if not manifests:
        print("No manifests found.", file=sys.stderr)
        return 1

    content = render_page(manifests)
    if not content.endswith("\n"):
        content += "\n"

    if args.stdout:
        print(content, end="")
        return 0

    if args.check:
        current = PAGES_PATH.read_text(encoding="utf-8") if PAGES_PATH.exists() else ""
        if current != content:
            print(
                "docs/index.md is out of date. Run: python _scripts/gen_pages.py",
                file=sys.stderr,
            )
            return 1
        print("docs/index.md is up to date.")
        return 0

    PAGES_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(str(PAGES_PATH), "w", encoding="utf-8") as f:
        f.write(content)
    print("Wrote {} ({} tools).".format(PAGES_PATH, len(manifests)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
