#!/usr/bin/env python3
"""Generate tools/README.md catalog listings from tools/*/tool.yaml manifests."""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = REPO_ROOT / "tools"
README_PATH = TOOLS_DIR / "README.md"
CATEGORIES_PATH = REPO_ROOT / "catalog" / "categories.yaml"
INDEX_PATH = REPO_ROOT / "catalog" / "index.yaml"

README_HEADER = """<!-- Generated by _scripts/gen_readme.py. Do not edit by hand. -->

# Tool catalog

Tools in this repository, grouped by category. Kind, Docker image, and KGpipe
task refs live on each tool's README.

"""


def load_yaml(path):
    with open(str(path), encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_category_meta():
    return load_yaml(CATEGORIES_PATH).get("categories", {})


def load_featured_ids():
    featured = load_yaml(INDEX_PATH).get("featured", [])
    return list(featured) if featured else []


def load_manifests():
    manifests = []
    for path in sorted(TOOLS_DIR.glob("*/tool.yaml")):
        if path.parent.name == "_template":
            continue
        data = load_yaml(path)
        data["_path"] = path.parent
        manifests.append(data)
    return manifests


def humanize_category(key):
    spaced = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", key)
    if not spaced:
        return key
    return spaced[0] + spaced[1:].lower()


def format_tool_line(manifest):
    description = (manifest.get("description") or "").strip()
    name = manifest["name"]
    tool_id = manifest["id"]
    status = manifest["status"]
    if description:
        return "- **[{name}]({id}/README.md)** — {description} *({status})*".format(
            name=name, id=tool_id, description=description, status=status
        )
    return "- **[{name}]({id}/README.md)** *({status})*".format(
        name=name, id=tool_id, status=status
    )


def generate_featured(manifests, featured_ids):
    by_id = {m["id"]: m for m in manifests}
    missing = [tool_id for tool_id in featured_ids if tool_id not in by_id]
    if missing:
        raise SystemExit(
            "catalog/index.yaml featured ids not found: {}".format(", ".join(missing))
        )
    if not featured_ids:
        return ""
    lines = ["## Featured", ""]
    for tool_id in featured_ids:
        lines.append(format_tool_line(by_id[tool_id]))
    lines.append("")
    return "\n".join(lines) + "\n"


def generate_listings(manifests, categories):
    by_category = defaultdict(list)
    for manifest in manifests:
        for cat in manifest.get("categories", ["DatasetUtility"]):
            by_category[cat].append(manifest)

    ordered = [key for key in categories if key in by_category]
    extra = sorted(key for key in by_category if key not in categories)

    lines = []
    for category in ordered + extra:
        lines.append("## {}".format(humanize_category(category)))
        lines.append("")
        cat_desc = categories.get(category, {}).get("description")
        if cat_desc:
            lines.append(cat_desc.rstrip("."))
            lines.append("")
        for manifest in sorted(by_category[category], key=lambda item: item["name"].lower()):
            lines.append(format_tool_line(manifest))
        lines.append("")
    return "\n".join(lines) + "\n"


def render_readme(manifests):
    categories = load_category_meta()
    featured_ids = load_featured_ids()
    return (
        README_HEADER
        + generate_featured(manifests, featured_ids)
        + generate_listings(manifests, categories)
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    manifests = load_manifests()
    if not manifests:
        print("No manifests found.", file=sys.stderr)
        return 1

    content = render_readme(manifests)
    if not content.endswith("\n"):
        content += "\n"

    if args.stdout:
        print(content, end="")
        return 0

    if args.check:
        current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else ""
        if current != content:
            print(
                "tools/README.md is out of date. Run: python _scripts/gen_readme.py",
                file=sys.stderr,
            )
            return 1
        print("tools/README.md is up to date.")
        return 0

    with open(str(README_PATH), "w", encoding="utf-8") as f:
        f.write(content)
    print("Wrote {} ({} tools).".format(README_PATH, len(manifests)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
