#!/usr/bin/env python3
"""Generate GitHub Actions docker-matrix workflow from tool.yaml ci flags."""

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = REPO_ROOT / "tools"
WORKFLOW_PATH = REPO_ROOT / ".github" / "workflows" / "docker-matrix.yml"


def discover_docker_tools():
    tools = []
    for path in sorted(TOOLS_DIR.glob("*/tool.yaml")):
        if path.parent.name == "_template":
            continue
        with open(str(path), encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if data.get("ci", {}).get("docker_build"):
            tools.append(data)
    return tools


def generate_workflow(tools):
    tool_ids = [t["id"] for t in tools]
    matrix_json = ", ".join('"{}"'.format(t) for t in tool_ids)

    return """# Generated by _scripts/gen_ci.py — do not edit by hand.
name: Docker build and test

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'tools/**'
      - '_scripts/**'
      - '.github/workflows/docker-matrix.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [{matrix}]
    steps:
      - uses: actions/checkout@v4

      - name: Build and test ${{{{ matrix.tool }}}}
        run: |
          TOOL_DIR="tools/${{{{ matrix.tool }}}}/docker"
          if [ ! -d "$TOOL_DIR" ]; then
            echo "Missing $TOOL_DIR"
            exit 1
          fi
          make -C "$TOOL_DIR" docker_build
          make -C "$TOOL_DIR" docker_test || true
""".format(matrix=matrix_json)


def main():
    tools = discover_docker_tools()
    if not tools:
        print("No tools with ci.docker_build found.", file=sys.stderr)
        return 1

    WORKFLOW_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(str(WORKFLOW_PATH), "w", encoding="utf-8") as f:
        f.write(generate_workflow(tools))
    print("Wrote {} ({} tools).".format(WORKFLOW_PATH, len(tools)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
